FROM squidfunk/mkdocs-material
RUN pip install -U wheel
RUN pip install fontawesome_markdown markdown mdx_truly_sane_lists mkdocs mkdocs-awesome-pages-plugin mkdocs-exclude mkdocs-macros-plugin mkdocs-material mkdocs-same-dir mkdocs-static-i18n mike plantuml-markdown pymdown-extensions python-markdown-math
RUN pip install -U git+https://github.com/jimporter/mike
RUN pip install mkdocs-material 